{% set name = "Axelrod" %}
{% set version = "4.11.0" %}
{% set sha256 = "e906d98767d8eb52a85492268e926088f661600173a1c1d1da3e7c53697f9937" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [py2k]

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.9.2
    - matplotlib-base >=1.4.2
    - tqdm >=3.4.0
    - prompt_toolkit >=1.0.7,<2
    - scipy >=0.19.0
    - dask >=0.11.0
    - pandas >=0.18.1
    - toolz >=0.8.0
    - cloudpickle >=0.2.1

test:
  imports:
    - axelrod
    - axelrod.data
    - axelrod.strategies
    - axelrod.tests

about:
  home: http://github.com/Axelrod-Python/Axelrod
  license: MIT
  license_file: LICENSE.txt
  summary: Research tool for Iterated Prisoners Dilemma in Python

  description: |
    Axelrod is a library for conducting research in Iterated Prisoner's
    Dilemma and enable reproducibilty of research on Iterated Prisoner's
    Dilemma. The library contains over 150 strategies for IPD and supports 
    Python 3.5 and 3.6
  doc_url: http://axelrod.readthedocs.io
  dev_url: https://github.com/Axelrod-Python/Axelrod

extra:
  recipe-maintainers:
    - drvinceknight
    - marcharper
    - meatballs
    - souravsingh
