travis:
  secure:
    BINSTAR_TOKEN: psJfWf9zWD2cM53MLTUzvELwBcFCd7Zm7sfCpmGJ2+mwevzjCq4kZVDJyvECsBGz52Ekk7++xiIas/nA3CwzkcPpYUHF3Km8qDsX5LivwXvhc4xGg6hT7ei/Ndc1vABhBgy1hiOKBH7rUPRMieFIkky71kWAt6NRz4Rc8+yBy8aAuDR3s2BxwFFAMqL8hHPEx4UO4t9XCjlu8fSjjFLIv/ti6ynfJghzJd1oQHCPgbO7DXzzIciJiNHSqk87Xy9bVItl3nSp4bvPF3p5PuIGHqHDhk+vB+P7LL3XZcmn/fomxNys+QHIOgfIIT6qYKrV3lPTOWsNvt+CkLK3xRexSOn3gJU6XlRYlEV9SCBvcp6koOGwcdH/Ft4ZV5I+7kL7PlQmvvqcUqY76OxpRVZzmyb02BChYGY2UUVTQa7M8l0RN/B6YOulwIfIbBFBxd9DsaqvVJvyev+1CFLssRnvN0HPel8Ye9W+TKMiCneUo2aLSto56e7Gk7X/7P1IZPBIrRTjOpoJL/PCpsMUxnL40F0KhFUzOlK/pdcS/Z1GoD2gvs24zWQPw0UpmFzsC/ZIagve48CTf24yaYK4IZD3qDXguMavoFweYbGJd7fHjcTqY/huvxWJa5v0myfIHdTKiAebA6+2k56yy30AO4WRWp+Jj0SBcIUPyZRdDH2cM5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
