appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WeptQpw6ZMRnI/Ig+v5ZJ/78vJtj3rcpVBYoGjwHneMUJTVYeLS19sPQB/kSSYvqADlyz2skjXWgahB7sPmR/EL8P/c8PZDDxQRb2+OKWGE3aF13/dzr398Sk78pM6nw/Q0j3wvYkv2/2ZY2TuVUILwG1GkoPHF3oMI8j65JnQwIqP/HZ+zFN9iEwSY17SeQ9r/MJ1sjW3uBWV8sYdYl0Hk8UZs9nTtZyx20cVeXcF56+XaXSYEjZSvB+ghJ8Q+iqEYVIJ68CYqrLhTTjO7cjHmUBOEqnGAGIfd82KGSr5HkSUimEJ9VztkmpGTcgo9w3zSHviMrr+dO8UC9WBd+K3el0RCv6134iV7d0+ReR3JyABdxGMzEmUTR+Bn3n0nfCgaDtZM1HJF8NqumeQfXLs+oooHXqidVD+Pd1X8KAD24iZ22dIX1u68FZc66fa7s+A6IBVJQXRdyO4hOP9oKIwGbCuP1b2rxJg/YOiUj+iry+3D3/Qva+99fwUzERnFeXtBQQmy+AYtBTuvzR9A40tIfZejS85Ju1slvzc4pw7GrcwBbtOq5EZAWsaXfRfJc+EigODI0RFwLwUfLCj4sX8EpPJguE3ye7c9v3yjvJenTEXJgn7BfK5/Sn6H6FNfjUJJ+Y9jPuADMYshempxOKsFrYUSi9GcUOEV+GqiJA0M=}
